/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package MonadCatchIO-transformers-0.3.1.3 */
#define VERSION_MonadCatchIO_transformers "0.3.1.3"
#define MIN_VERSION_MonadCatchIO_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 1)

/* package aeson-0.8.1.1 */
#define VERSION_aeson "0.8.1.1"
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 1)

/* package aeson-pretty-0.7.2 */
#define VERSION_aeson_pretty "0.7.2"
#define MIN_VERSION_aeson_pretty(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 2)

/* package aeson-utils-0.3.0.2 */
#define VERSION_aeson_utils "0.3.0.2"
#define MIN_VERSION_aeson_utils(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)

/* package asn1-encoding-0.9.2 */
#define VERSION_asn1_encoding "0.9.2"
#define MIN_VERSION_asn1_encoding(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 2)

/* package asn1-parse-0.9.1 */
#define VERSION_asn1_parse "0.9.1"
#define MIN_VERSION_asn1_parse(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 1)

/* package asn1-types-0.3.0 */
#define VERSION_asn1_types "0.3.0"
#define MIN_VERSION_asn1_types(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)

/* package async-2.0.2 */
#define VERSION_async "2.0.2"
#define MIN_VERSION_async(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 2)

/* package attoparsec-0.13.0.1 */
#define VERSION_attoparsec "0.13.0.1"
#define MIN_VERSION_attoparsec(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 0)

/* package base-4.8.1.0 */
#define VERSION_base "4.8.1.0"
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  8 || \
  (major1) == 4 && (major2) == 8 && (minor) <= 1)

/* package blaze-html-0.8.1.0 */
#define VERSION_blaze_html "0.8.1.0"
#define MIN_VERSION_blaze_html(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 1)

/* package bytestring-0.10.6.0 */
#define VERSION_bytestring "0.10.6.0"
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 6)

/* package case-insensitive-1.2.0.4 */
#define VERSION_case_insensitive "1.2.0.4"
#define MIN_VERSION_case_insensitive(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 0)

/* package configifier-0.0.5 */
#define VERSION_configifier "0.0.5"
#define MIN_VERSION_configifier(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  0 || \
  (major1) == 0 && (major2) == 0 && (minor) <= 5)

/* package containers-0.5.6.2 */
#define VERSION_containers "0.5.6.2"
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 6)

/* package cryptonite-0.6 */
#define VERSION_cryptonite "0.6"
#define MIN_VERSION_cryptonite(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 0)

/* package digestive-functors-0.8.0.0 */
#define VERSION_digestive_functors "0.8.0.0"
#define MIN_VERSION_digestive_functors(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 0)

/* package digestive-functors-blaze-0.6.0.6 */
#define VERSION_digestive_functors_blaze "0.6.0.6"
#define MIN_VERSION_digestive_functors_blaze(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 0)

/* package digestive-functors-snap-0.6.1.3 */
#define VERSION_digestive_functors_snap "0.6.1.3"
#define MIN_VERSION_digestive_functors_snap(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 1)

/* package directory-1.2.2.0 */
#define VERSION_directory "1.2.2.0"
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 2)

/* package either-4.4.1 */
#define VERSION_either "4.4.1"
#define MIN_VERSION_either(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  4 || \
  (major1) == 4 && (major2) == 4 && (minor) <= 1)

/* package email-validate-2.1.3 */
#define VERSION_email_validate "2.1.3"
#define MIN_VERSION_email_validate(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 3)

/* package errors-2.0.0 */
#define VERSION_errors "2.0.0"
#define MIN_VERSION_errors(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 0)

/* package filepath-1.4.0.0 */
#define VERSION_filepath "1.4.0.0"
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 0)

/* package functor-infix-0.0.3 */
#define VERSION_functor_infix "0.0.3"
#define MIN_VERSION_functor_infix(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  0 || \
  (major1) == 0 && (major2) == 0 && (minor) <= 3)

/* package generic-aeson-0.2.0.7 */
#define VERSION_generic_aeson "0.2.0.7"
#define MIN_VERSION_generic_aeson(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 0)

/* package hslogger-1.2.9 */
#define VERSION_hslogger "1.2.9"
#define MIN_VERSION_hslogger(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 9)

/* package http-client-0.4.23 */
#define VERSION_http_client "0.4.23"
#define MIN_VERSION_http_client(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 23)

/* package http-media-0.6.2 */
#define VERSION_http_media "0.6.2"
#define MIN_VERSION_http_media(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 2)

/* package http-reverse-proxy-0.4.2 */
#define VERSION_http_reverse_proxy "0.4.2"
#define MIN_VERSION_http_reverse_proxy(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 2)

/* package http-types-0.8.6 */
#define VERSION_http_types "0.8.6"
#define MIN_VERSION_http_types(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 6)

/* package lens-4.12.3 */
#define VERSION_lens "4.12.3"
#define MIN_VERSION_lens(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  12 || \
  (major1) == 4 && (major2) == 12 && (minor) <= 3)

/* package lifted-base-0.2.3.6 */
#define VERSION_lifted_base "0.2.3.6"
#define MIN_VERSION_lifted_base(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 3)

/* package lio-0.11.5.0 */
#define VERSION_lio "0.11.5.0"
#define MIN_VERSION_lio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  11 || \
  (major1) == 0 && (major2) == 11 && (minor) <= 5)

/* package mime-mail-0.4.10 */
#define VERSION_mime_mail "0.4.10"
#define MIN_VERSION_mime_mail(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 10)

/* package monad-control-1.0.0.4 */
#define VERSION_monad_control "1.0.0.4"
#define MIN_VERSION_monad_control(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 0)

/* package mtl-2.2.1 */
#define VERSION_mtl "2.2.1"
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 1)

/* package old-locale-1.0.0.7 */
#define VERSION_old_locale "1.0.0.7"
#define MIN_VERSION_old_locale(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 0)

/* package postgresql-simple-0.4.10.0 */
#define VERSION_postgresql_simple "0.4.10.0"
#define MIN_VERSION_postgresql_simple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 10)

/* package pretty-show-1.6.8.2 */
#define VERSION_pretty_show "1.6.8.2"
#define MIN_VERSION_pretty_show(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 8)

/* package random-1.1 */
#define VERSION_random "1.1"
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)

/* package resource-pool-0.2.3.2 */
#define VERSION_resource_pool "0.2.3.2"
#define MIN_VERSION_resource_pool(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 3)

/* package safe-0.3.9 */
#define VERSION_safe "0.3.9"
#define MIN_VERSION_safe(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 9)

/* package sandi-0.3.5 */
#define VERSION_sandi "0.3.5"
#define MIN_VERSION_sandi(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 5)

/* package scrypt-0.5.0 */
#define VERSION_scrypt "0.5.0"
#define MIN_VERSION_scrypt(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 0)

/* package servant-0.5 */
#define VERSION_servant "0.5"
#define MIN_VERSION_servant(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 0)

/* package servant-docs-0.5 */
#define VERSION_servant_docs "0.5"
#define MIN_VERSION_servant_docs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 0)

/* package servant-server-0.5 */
#define VERSION_servant_server "0.5"
#define MIN_VERSION_servant_server(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 0)

/* package servant-session-0.5 */
#define VERSION_servant_session "0.5"
#define MIN_VERSION_servant_session(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 0)

/* package snap-0.14.0.6 */
#define VERSION_snap "0.14.0.6"
#define MIN_VERSION_snap(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  14 || \
  (major1) == 0 && (major2) == 14 && (minor) <= 0)

/* package snap-core-0.9.8.0 */
#define VERSION_snap_core "0.9.8.0"
#define MIN_VERSION_snap_core(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 8)

/* package snap-server-0.9.5.1 */
#define VERSION_snap_server "0.9.5.1"
#define MIN_VERSION_snap_server(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 5)

/* package string-conversions-0.4 */
#define VERSION_string_conversions "0.4"
#define MIN_VERSION_string_conversions(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 0)

/* package text-1.2.1.3 */
#define VERSION_text "1.2.1.3"
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 1)

/* package thyme-0.3.5.5 */
#define VERSION_thyme "0.3.5.5"
#define MIN_VERSION_thyme(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 5)

/* package time-1.5.0.1 */
#define VERSION_time "1.5.0.1"
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 0)

/* package transformers-0.4.2.0 */
#define VERSION_transformers "0.4.2.0"
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 2)

/* package unordered-containers-0.2.5.1 */
#define VERSION_unordered_containers "0.2.5.1"
#define MIN_VERSION_unordered_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 5)

/* package uri-bytestring-0.1.9 */
#define VERSION_uri_bytestring "0.1.9"
#define MIN_VERSION_uri_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 9)

/* package wai-3.0.3.0 */
#define VERSION_wai "3.0.3.0"
#define MIN_VERSION_wai(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  0 || \
  (major1) == 3 && (major2) == 0 && (minor) <= 3)

/* package warp-3.1.3 */
#define VERSION_warp "3.1.3"
#define MIN_VERSION_warp(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 3)

/* package x509-1.6.1 */
#define VERSION_x509 "1.6.1"
#define MIN_VERSION_x509(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 1)

/* package x509-validation-1.6.2 */
#define VERSION_x509_validation "1.6.2"
#define MIN_VERSION_x509_validation(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 2)

/* tool alex-3.1.3 */
#define TOOL_VERSION_alex "3.1.3"
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 3)

/* tool cpphs-1.19.3 */
#define TOOL_VERSION_cpphs "1.19.3"
#define MIN_TOOL_VERSION_cpphs(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  19 || \
  (major1) == 1 && (major2) == 19 && (minor) <= 3)

/* tool gcc-4.9.2 */
#define TOOL_VERSION_gcc "4.9.2"
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  9 || \
  (major1) == 4 && (major2) == 9 && (minor) <= 2)

/* tool ghc-7.10.2 */
#define TOOL_VERSION_ghc "7.10.2"
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  10 || \
  (major1) == 7 && (major2) == 10 && (minor) <= 2)

/* tool ghc-pkg-7.10.2 */
#define TOOL_VERSION_ghc_pkg "7.10.2"
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  10 || \
  (major1) == 7 && (major2) == 10 && (minor) <= 2)

/* tool haddock-2.16.1 */
#define TOOL_VERSION_haddock "2.16.1"
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  16 || \
  (major1) == 2 && (major2) == 16 && (minor) <= 1)

/* tool happy-1.19.4 */
#define TOOL_VERSION_happy "1.19.4"
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  19 || \
  (major1) == 1 && (major2) == 19 && (minor) <= 4)

/* tool hpc-0.67 */
#define TOOL_VERSION_hpc "0.67"
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)

/* tool hsc2hs-0.67 */
#define TOOL_VERSION_hsc2hs "0.67"
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)

/* tool hscolour-1.22 */
#define TOOL_VERSION_hscolour "1.22"
#define MIN_TOOL_VERSION_hscolour(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  22 || \
  (major1) == 1 && (major2) == 22 && (minor) <= 0)

/* tool pkg-config-0.28 */
#define TOOL_VERSION_pkg_config "0.28"
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  28 || \
  (major1) == 0 && (major2) == 28 && (minor) <= 0)

/* tool strip-2.25 */
#define TOOL_VERSION_strip "2.25"
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  25 || \
  (major1) == 2 && (major2) == 25 && (minor) <= 0)

#define CURRENT_PACKAGE_KEY "thent_1ovKESpwULT2SOP0MifGpS"

